import alertImage from '../../assets/alertTriangle.png';
import sample from '../../assets/image.png';
import material from '../../assets/imageMaterial.png';
import defaultImage from '../../assets/imagemDefault.png';
import placeholder from '../../assets/imagePlaceholder.png';

const { origin } = window.location;

const imagePlaceholder = `${origin}${placeholder}`;
const imageDefault = `${origin}${defaultImage}`;
const imageMaterial = `${origin}${material}`;
const imageSample = `${origin}${sample}`;

export const editorButtons = {
  title:
    '<h1 style="text-align: center; font-family: verdana, geneva, sans-serif;font-style: normal;font-weight: 700;font-size: 30px;color: #002060">Título</h1><br>',
  titleWithImage: `<table style="border-collapse:collapse;width: 100%;"><tbody><tr><td style="width: 50%; text-align: right; border: none; padding: 16px;"><img style="max-height: 300px" src="${imagePlaceholder}" alt=""></td><td style="width: 50%; text-align: left; border: none; padding: 16px;"><h1><span style="font-size: 30px; color: rgb(0, 32, 96);">Texto</span></h1></td></tr></tbody></table><br>`,
  textWithImage: `<table style="border-collapse: collapse; text-align: center; width: 100%"><tbody><tr><td style="width: 50%; border: none"><span style="font-family: verdana, geneva, sans-serif; font-size: 24px; color: rgb(102, 102, 102);">Insira seu texto aqui</span><br></td><td style="width: 50%; border: none"><p><img src="${imageDefault}" alt=""></p><p style="font-size: 0.8rem;">Insira seu texto aqui</p></td></tr></tbody></table><br>`,
  text: '<p style="width: 70%; font-family: verdana, geneva, sans-serif; font-size: 18px; color: rgb(102, 102, 102); text-align: justify; margin-right: auto; margin-left: auto;">A ALGETEC foi fundada em 2011 por dois professores que sentiam na “pele" a necessidade de aliar teoria com prática na rotina de sala de aula, com o intuito de provocar maior engajamento dos estudantes. As primeiras bancadas didáticas foram desenvolvidas na garagem do escritório da empresa. A equipe montada para iniciar a trajetória sempre teve como premissas: qualidade e zelo com as questões didáticas de cada equipamento. Essa equipe desbravadora continua conosco até hoje!</p><br>',
  textWithColumns:
    '<table style="border-collapse: collapse; width: 100%; text-align: center;"><tbody><tr><td style="width: 50%; border: none;"><br><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;"><span style="font-size: 24px;">Insira seu texto aqui</span></p></td><td style="width: 50%; border: none;"><br><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;"><span style="font-size: 24px;">Insira seu texto aqui</span></p></td></tr></tbody></table><br>',
  textWithMultipleColumns: `<table style="border-collapse: collapse; width: 100%; text-align: center;"><tbody><tr><td style="width: 50%; border: none;"><br><img src="${imagePlaceholder}" alt=""><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;">Insira seu texto aqui</p></td><td style="width: 50%; border: none;"><br><img src="${imagePlaceholder}" alt=""><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;">Insira seu texto aqui</p></td></tr><tr><td style="width: 50%; border: none;"><br><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;"><span style="font-size: 24px;">Insira seu texto aqui</span></p></td><td style="width: 50%; border: none;"><br><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;"><span style="font-size: 24px;">Insira seu texto aqui</span></p></td></tr></tbody></table><br>`,
  list: '<div style="text-align: center;"><ul style="display: inline-block; text-align: left; font-family: verdana, geneva, sans-serif; list-style: none;"><li><span style="color: rgb(102, 102, 102); font-size: 24px;">Insira seu texto aqui</span></li><li><span style="color: rgb(102, 102, 102); font-size: 24px;">Insira seu texto aqui</span></li><li><span style="color: rgb(102, 102, 102); font-size: 24px;">Insira seu texto aqui</span></li><li><span style="color: rgb(102, 102, 102); font-size: 24px;">Insira seu texto aqui</span></li></ul></div><br>',
  imageContainer: `<table style="border-collapse: collapse; width: 100%; text-align: center;"><tbody><tr><td style="width: 25%; border: none;"><img src="${imagePlaceholder}" alt=""><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;">Insira seu texto aqui</p></td><td style="width: 25%; border: none;"><img src="${imagePlaceholder}" alt=""><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;">Insira seu texto aqui</p></td><td style="width: 25%; border: none;"><img src="${imagePlaceholder}" alt=""><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;">Insira seu texto aqui</p></td><td style="width: 25%; border: none;"><img src="${imagePlaceholder}" alt=""><p style="font-family: verdana, geneva, sans-serif; font-style: normal; font-weight: 250; line-height: 24px; color: rgb(102, 102, 102); font-size: 18px;">Insira seu texto aqui</p></td></tr></tbody></table><br>`,
  boxMessageWithImageRight: `<table style="border-collapse:collapse;width: 100%;"><tbody><tr><td style="width: 50%; text-align: right; padding: 16px; border: none;"><div style="display: flex; flex-wrap: wrap; justify-content: right; align-items: center;"><p style="word-break: break-all; background-color: rgb(57, 163, 239); max-width: 26vw; display: flex; height: auto; padding: 20px 25px; box-shadow: rgba(0, 0, 0, 0.25) 0 4px 4px, rgba(0, 0, 0, 0.25) 0 12px 12px; border-radius: 4px;"><span style="font-family: verdana, geneva, sans-serif; font-size: 18px; color: #faf9f6;">Insira seu texto aqui</span></p></div></td><td style="width: 50%; padding: 16px; border: none;"><img src="${imageMaterial}" alt="" style="float: left;"></td></tr></tbody></table><br>`,
  boxMessageWithImageLeft: `<table style="border-collapse:collapse;width: 100%;"><tbody><tr><td style="width: 50%; text-align: right; padding: 16px; border: none;"><img src="${imageMaterial}" alt="" style="float: right;"></td><td style="width: 50%; text-align: left; padding: 16px; border: none;"><div style="display: flex; flex-wrap: wrap; justify-content: left; align-items: center;"><p style="word-break: break-all; background-color: rgb(57, 163, 239); max-width: 26vw; display: flex; height: auto; padding: 20px 25px; box-shadow: rgba(0, 0, 0, 0.25) 0 4px 4px, rgba(0, 0, 0, 0.25) 0 12px 12px; border-radius: 4px;"><span style="font-family: verdana, geneva, sans-serif; font-size: 18px; color: #faf9f6;">Insira seu texto aqui</span></p></div></td></tr></tbody></table><br>`,
  boxMessageWithImageInside: `<table style="border-collapse: collapse; max-width: 490px; min-height: 160px; box-shadow: rgba(0, 0, 0, 0.25) 0 4px 4px, rgba(0, 0, 0, 0.25) 0 12px 12px; border-radius: 4px; text-align: center; margin-left: auto; margin-right: auto"><tbody><tr><td style="width: 40%; background-color: rgb(57, 163, 239); border: none; padding: 20px; border-radius: 4px 0 0 4px;"><img src="${imageSample}" alt="" style="width: 15vw"></td><td style="width: 60%; background-color: rgb(57, 163, 239); border: none; border-radius: 0 4px 4px 0; padding: 16px 16px 16px 0;"><span style="font-family: verdana, geneva, sans-serif; font-size: 16px; color: rgb(255, 255, 255);">Insira seu texto aqui</span></td></tr></tbody></table><br>`,
  boxMessageWithIconInside: `<table style="border-collapse: collapse; max-width: 490px; min-height: 160px; box-shadow: rgba(0, 0, 0, 0.25) 0 4px 4px, rgba(0, 0, 0, 0.25) 0 12px 12px; border-radius: 4px; text-align: center; margin-left: auto; margin-right: auto"><tbody><tr><td style="width: 40%; background-color: rgb(57, 163, 239); border: none; padding: 20px; border-radius: 4px 0 0 4px;"><img src="${alertImage}" alt="" style="width: 10vw"></td><td style="width: 60%; background-color: rgb(57, 163, 239); border: none; border-radius: 0 4px 4px 0; padding: 16px 16px 16px 0;"><span style="font-family: verdana, geneva, sans-serif; font-size: 16px; color: rgb(255, 255, 255);">Insira seu texto aqui</span></td></tr></tbody></table><br>`,
  boxImage: `<p style="text-align: center;"><img src="${imageDefault}" alt=""></p><p style="font-size: 0.8rem; text-align: center;">Insira seu texto aqui</p><br>`,
};
